//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apple_Battery_Check.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apple_Battery_Check.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   (Simge) öğesine benzeyen System.Drawing.Icon türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Icon Battery_Charging {
            get {
                object obj = ResourceManager.GetObject("Battery_Charging", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   _ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BOT_SLASH {
            get {
                return ResourceManager.GetString("BOT_SLASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .TXT benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EXTANSION_FORMAT {
            get {
                return ResourceManager.GetString("EXTANSION_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HH-mm-ss_dd.MM.yyyy benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FILE_NAME_FORMAT {
            get {
                return ResourceManager.GetString("FILE_NAME_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string KEY_HDQ {
            get {
                return ResourceManager.GetString("KEY_HDQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   B benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string KEY_I2C {
            get {
                return ResourceManager.GetString("KEY_I2C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --/-- benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LBL_DEFAULT_TEXT {
            get {
                return ResourceManager.GetString("LBL_DEFAULT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BQ27 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PREFIX_CONTROLLER {
            get {
                return ResourceManager.GetString("PREFIX_CONTROLLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0x benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PREFIX_HEXADECIMAL {
            get {
                return ResourceManager.GetString("PREFIX_HEXADECIMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///    -  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SPACE_TEXT {
            get {
                return ResourceManager.GetString("SPACE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    mAh benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SUFFIX_CAPACITY {
            get {
                return ResourceManager.GetString("SUFFIX_CAPACITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   °C benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SUFFIX_CELSIUS_DEGREE {
            get {
                return ResourceManager.GetString("SUFFIX_CELSIUS_DEGREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    A benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SUFFIX_CURRENT {
            get {
                return ResourceManager.GetString("SUFFIX_CURRENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    mA benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SUFFIX_CURRENT_MA {
            get {
                return ResourceManager.GetString("SUFFIX_CURRENT_MA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   % benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SUFFIX_PERCENT {
            get {
                return ResourceManager.GetString("SUFFIX_PERCENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    W benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SUFFIX_POWER {
            get {
                return ResourceManager.GetString("SUFFIX_POWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///    mW benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SUFFIX_POWER_MW {
            get {
                return ResourceManager.GetString("SUFFIX_POWER_MW", resourceCulture);
            }
        }
        
        /// <summary>
        ///    V benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SUFFIX_VOLTAGE {
            get {
                return ResourceManager.GetString("SUFFIX_VOLTAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    mV benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SUFFIX_VOLTAGE_MV {
            get {
                return ResourceManager.GetString("SUFFIX_VOLTAGE_MV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HDQ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TEXT_HDQ {
            get {
                return ResourceManager.GetString("TEXT_HDQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I2C benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TEXT_I2C {
            get {
                return ResourceManager.GetString("TEXT_I2C", resourceCulture);
            }
        }
    }
}
