//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apple_Battery_Check.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apple_Battery_Check.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon Battery_Charging {
            get {
                object obj = ResourceManager.GetObject("Battery_Charging", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _.
        /// </summary>
        internal static string BOT_SLASH {
            get {
                return ResourceManager.GetString("BOT_SLASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .TXT.
        /// </summary>
        internal static string EXTANSION_FORMAT {
            get {
                return ResourceManager.GetString("EXTANSION_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HH-mm-ss_dd.MM.yyyy.
        /// </summary>
        internal static string FILE_NAME_FORMAT {
            get {
                return ResourceManager.GetString("FILE_NAME_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A.
        /// </summary>
        internal static string KEY_HDQ {
            get {
                return ResourceManager.GetString("KEY_HDQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на B.
        /// </summary>
        internal static string KEY_I2C {
            get {
                return ResourceManager.GetString("KEY_I2C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на --/--.
        /// </summary>
        internal static string LBL_DEFAULT_TEXT {
            get {
                return ResourceManager.GetString("LBL_DEFAULT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на bq27.
        /// </summary>
        internal static string PREFIX_CONTROLLER {
            get {
                return ResourceManager.GetString("PREFIX_CONTROLLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0x.
        /// </summary>
        internal static string PREFIX_HEXADECIMAL {
            get {
                return ResourceManager.GetString("PREFIX_HEXADECIMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  - .
        /// </summary>
        internal static string SPACE_TEXT {
            get {
                return ResourceManager.GetString("SPACE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  мАч.
        /// </summary>
        internal static string SUFFIX_CAPACITY {
            get {
                return ResourceManager.GetString("SUFFIX_CAPACITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  °C.
        /// </summary>
        internal static string SUFFIX_CELSIUS_DEGREE {
            get {
                return ResourceManager.GetString("SUFFIX_CELSIUS_DEGREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  %.
        /// </summary>
        internal static string SUFFIX_PERCENT {
            get {
                return ResourceManager.GetString("SUFFIX_PERCENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  В.
        /// </summary>
        internal static string SUFFIX_VOLTAGE {
            get {
                return ResourceManager.GetString("SUFFIX_VOLTAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HDQ.
        /// </summary>
        internal static string TEXT_HDQ {
            get {
                return ResourceManager.GetString("TEXT_HDQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на I2C.
        /// </summary>
        internal static string TEXT_I2C {
            get {
                return ResourceManager.GetString("TEXT_I2C", resourceCulture);
            }
        }
    }
}
